### PR TITLE
Add testcase for srcset attribute in source tag

### LINKED ISSUE #6365: Image not loaded from medium
Environment

- wallabag version (or git revision) that exhibits the issue:  2.5.2
- How did you install wallabag? Via git clone
- php version: 7.4
- OS: Fedora 37
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL/MariaDB

Steps to reproduce/test case

- Add URL: https://towardsdatascience.com/equal-size-spectral-clustering-cce65c6f9ba3
- The aricle is loaded correctly but without images
I got the same error using app.wallabag.it

### PR DESCRIPTION
**Pull request by Kdecherf**
Fixes https://github.com/wallabag/wallabag/issues/6365

This PR is based on #14

### CODE REVIEW

**Comment by jtojnar** [comment]
~~Weird, this was supposed to be fixed in 1.2.12: http://www.bioinformatics.org/phplabware/forum/viewtopic.php?pid=1006#p1006~~ Never mind, that was `sizes`.

**Comment by jtojnar** [comment]
Reported upstream: http://www.bioinformatics.org/phplabware/forum/viewtopic.php?pid=1014

**Comment by Kdecherf** [comment]
@jtojnar do you want to wait for an upstream update?

**Comment by jtojnar** [comment]
Either way sounds good to me. I will leave it up to you.

**Comment by j0k3r** [comment]
Could you rebase against the master to remove the extra first commit?

**Comment by Kdecherf** [comment]
@j0k3r done

**Review by j0k3r — APPROVED** [review]

**Comment by Kdecherf** [comment]
I've rebased this PR on #16, keeping just a new testcase

**Pull request merged**
