### PR TITLE
Update to upstream 1.2.11

### PR DESCRIPTION
**Pull request by Kdecherf**
I give up on keeping coding style because the original author refactored his file several times since our last upstream update and it's way to hard to keep our cs-fixer happy with it.

For this PR I took the `htmLawed.php` from the version 1.2.11 and manually applied back the following commits from our history:

- be3bea268e0ab611b7d3db3696aa17cd655ed5e4
- b7eba15917322afe47bf76bf9f74469122bc0a37
- 136ba9bf07c2c23d94f5f1674458a92f8f82e644
- 16da2b61f0b645aa575eeb47a79758b0cfce061f
- 703fd8bc29d1a8ef900335f4e60e2f63e6ae72cd
- 06369f2d11b220359c863c089a3e864f78777d26
- 36fd540d6aabca36fe4913eaa7328f2e65429294

### CODE REVIEW

**Comment by j0k3r** [comment]
But the CS is still applied to the changes of the PR. You only removed the GitHub Actions not your changes.
Changes doesn't seems to reflect commits you mentioned in the description. 🤔

**Comment by Kdecherf** [comment]
> But the CS is still applied to the changes of the PR. You only removed the GitHub Actions not your changes. Changes doesn't seems to reflect commits you mentioned in the description.

Why are you thinking that the mentioned commits weren't applied in this PR?

**Comment by Kdecherf** [comment]
For example, changes from https://github.com/fossar/HTMLawed/commit/36fd540d6aabca36fe4913eaa7328f2e65429294 are there: https://github.com/fossar/HTMLawed/pull/13/files#diff-de6a7cbbecb3f5429086abe7dac1ffd2e5bf4a084f5a6acda3e841d00a5c4022R1200-R1207

**Comment by j0k3r** [comment]
I can't remember why I said that..

**Pull request merged**
