### PR TITLE
Allow phrasing content (#pcdata) inside ruby tags

### PR DESCRIPTION
**Pull request by Kdecherf**
Fixes https://github.com/wallabag/wallabag/issues/3710

### CODE REVIEW

**Comment by techexo** [comment]
To support this pull request, the [reference of HTML5 regarding ruby](https://www.w3.org/TR/html5/textlevel-semantics.html#the-ruby-element) contains multiple examples where the `ruby` element contains data.

**Comment by jtojnar** [comment]
Thank you but this is only a mirror – any contributions should go [upstream](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/), sent by e-mail according to http://www.bioinformatics.org/phplabware/forum/viewtopic.php?id=133. Though the only e-mail address I was able to find was a [PayPal username](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm#s4.9).

**Comment by j0k3r** [comment]
@jtojnar I agree it's only a mirror.

But getting that fix merged upstream seems to be really complex:
1. sending the code by email,
2. (eventually) getting a reply from the author,
3. fix provided upstream,
4. a new release, and
5. finally that repo updated with the latest release :face_with_head_bandage: 

Can't we accept PR on this repo and merge upstream from time to time when a release is done?

Otherwise, we should disable PR and issues for that repo and update the readme to explicitely explain why this repo exists and why we didn't accept contributions.

Also, if we finally choose not to approve contributions, my guess is that we (wallabag) are going to fork this repo to apply our own contributions :man_shrugging:

**Comment by jtojnar** [comment]
If you want to do this, I don't object. I just do not have the time to maintain this apart from pulling the new versions.

**Comment by j0k3r** [comment]
Ok I agree too.
We are not going to overtake the upstream just an easier way to push fixes instead of sending an email.

**Pull request merged**
